/**
 * Dominio diario — "Il Mio Tiro" (Piano_Sviluppo_App.md §4.4, BP §3.5).
 *
 * ⚠️  NESSUN numero di matricola. NESSUN documento di detenzione.
 * (BP §3.5.8, Piano §8.1 regola 1 e 2)
 */
import { pgTable, uuid, text, pgEnum, integer, boolean, timestamp, date, doublePrecision } from 'drizzle-orm/pg-core';
import { ranges } from './ranges.js';

export const firearmType = pgEnum('firearm_type', [
  'pistola',
  'revolver',
  'carabina',
  'fucile',
  'avancarica',
]);

export const targetScoringMode = pgEnum('target_scoring_mode', [
  'manuale',
  'automatico',
]);

export const maintenanceKind = pgEnum('maintenance_kind', [
  'pulizia',
  'usura_canna',
  'molla_recupero',
]);

// ---------------------------------------------------------------------------
// Armi
// ---------------------------------------------------------------------------
export const firearms = pgTable('firearms', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  nickname: text('nickname').notNull(),
  type: firearmType('type').notNull(),
  caliber: text('caliber').notNull(),
  yearAcquired: integer('year_acquired'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Sessioni di tiro
// ---------------------------------------------------------------------------
export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  rangeId: uuid('range_id').references(() => ranges.id),
  bookingId: uuid('booking_id'),
  rangeNameManual: text('range_name_manual'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  durationMinutes: integer('duration_min').notNull(),
  distanceMeters: integer('distance_m'),
  autoGenerated: boolean('auto_generated').notNull().default(false),
  confirmedByUser: boolean('confirmed_by_user').notNull().default(false),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Colpi sparati per sessione.
 *
 * `firearmId` non è più popolato dal client: l'armeria (tabella `firearms`)
 * è diventata dato solo-locale sul dispositivo dell'utente, mai trasmesso al
 * server (scelta di prodotto). `firearmLabel` conserva lo snapshot testuale
 * del soprannome dell'arma al momento della sessione, senza collegamento a
 * una riga server che potrebbe non esistere più. La colonna e la FK restano
 * per compatibilità storica ma sono opzionali.
 */
export const sessionShots = pgTable('session_shots', {
  id: uuid('id').primaryKey().defaultRandom(),
  sessionId: uuid('session_id')
    .notNull()
    .references(() => sessions.id, { onDelete: 'cascade' }),
  firearmId: uuid('firearm_id').references(() => firearms.id),
  firearmLabel: text('firearm_label'),
  caliber: text('caliber').notNull(),
  roundsFired: integer('rounds_fired').notNull(),
});

// ---------------------------------------------------------------------------
// Bersagli
// ---------------------------------------------------------------------------
/**
 * Bersagli. `firearmId`/`storageRef` non sono più garantiti: l'armeria è
 * dato solo-locale (come `session_shots.firearmId`, vedi migrazione 0009) e
 * la marcatura fori v1 non prevede upload foto, solo un diagramma. Restano
 * come colonne opzionali per compatibilità storica e per un eventuale
 * upload foto futuro.
 */
export const targets = pgTable('targets', {
  id: uuid('id').primaryKey().defaultRandom(),
  sessionId: uuid('session_id')
    .notNull()
    .references(() => sessions.id, { onDelete: 'cascade' }),
  firearmId: uuid('firearm_id').references(() => firearms.id),
  firearmLabel: text('firearm_label'),
  storageRef: text('storage_ref'),
  targetType: text('target_type'),
  distanceMeters: integer('distance_m'),
  scoringMode: targetScoringMode('scoring_mode').notNull().default('manuale'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Fori marcati dall'utente sul bersaglio.
 */
export const targetHoles = pgTable('target_holes', {
  id: uuid('id').primaryKey().defaultRandom(),
  targetId: uuid('target_id')
    .notNull()
    .references(() => targets.id, { onDelete: 'cascade' }),
  xMm: doublePrecision('x_mm').notNull(),
  yMm: doublePrecision('y_mm').notNull(),
  score: doublePrecision('score'),
});

// ---------------------------------------------------------------------------
// Regole di manutenzione
// ---------------------------------------------------------------------------
export const maintenanceRules = pgTable('maintenance_rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  firearmId: uuid('firearm_id')
    .notNull()
    .references(() => firearms.id, { onDelete: 'cascade' }),
  kind: maintenanceKind('kind').notNull(),
  intervalRounds: integer('interval_rounds').notNull(),
  lastDoneAtRounds: integer('last_done_at_rounds').notNull().default(0),
});
