/**
 * Sigle provinciali italiane (targa), nomenclatura ISTAT standard.
 *
 * Dato pubblico stabile: non contiene alcuna informazione su singole
 * strutture, solo il nome per esteso di ciascuna provincia a partire dalla
 * sigla. Elenco completo delle 107 province italiane, più 4 sigle storiche
 * sarde confluite in Sud Sardegna nel 2016 (VS Medio Campidano, CI
 * Carbonia-Iglesias, OG Ogliastra, OT Olbia-Tempio) — compaiono ancora in
 * fonti importate meno recenti, incluso il dataset comuni ISTAT usato per
 * comuni.ts. Non più limitato alle sole sigle del censimento originale:
 * usato anche per normalizzare province scritte come sigla da fonti
 * importate (es. Targetfun, vedi TARGETFUN_IMPORT_LOG.md) in
 * queries/ranges.ts.
 */
export const PROVINCIA_BY_SIGLA: Record<string, string> = {
  AG: 'Agrigento',
  AL: 'Alessandria',
  AN: 'Ancona',
  AO: 'Aosta',
  AP: 'Ascoli Piceno',
  AQ: "L'Aquila",
  AR: 'Arezzo',
  AT: 'Asti',
  AV: 'Avellino',
  BA: 'Bari',
  BG: 'Bergamo',
  BI: 'Biella',
  BL: 'Belluno',
  BN: 'Benevento',
  BO: 'Bologna',
  BR: 'Brindisi',
  BS: 'Brescia',
  BT: 'Barletta-Andria-Trani',
  BZ: 'Bolzano',
  CA: 'Cagliari',
  CB: 'Campobasso',
  CE: 'Caserta',
  CH: 'Chieti',
  CI: 'Sud Sardegna',
  CL: 'Caltanissetta',
  CN: 'Cuneo',
  CO: 'Como',
  CR: 'Cremona',
  CS: 'Cosenza',
  CT: 'Catania',
  CZ: 'Catanzaro',
  EN: 'Enna',
  FC: 'Forlì-Cesena',
  FE: 'Ferrara',
  FG: 'Foggia',
  FI: 'Firenze',
  FM: 'Fermo',
  FR: 'Frosinone',
  GE: 'Genova',
  GO: 'Gorizia',
  GR: 'Grosseto',
  IM: 'Imperia',
  IS: 'Isernia',
  KR: 'Crotone',
  LC: 'Lecco',
  LE: 'Lecce',
  LI: 'Livorno',
  LO: 'Lodi',
  LT: 'Latina',
  LU: 'Lucca',
  MB: 'Monza e della Brianza',
  MC: 'Macerata',
  ME: 'Messina',
  MI: 'Milano',
  MN: 'Mantova',
  MO: 'Modena',
  MS: 'Massa-Carrara',
  MT: 'Matera',
  NA: 'Napoli',
  NO: 'Novara',
  NU: 'Nuoro',
  OG: 'Sud Sardegna',
  OR: 'Oristano',
  OT: 'Sud Sardegna',
  PA: 'Palermo',
  PC: 'Piacenza',
  PD: 'Padova',
  PE: 'Pescara',
  PG: 'Perugia',
  PI: 'Pisa',
  PN: 'Pordenone',
  PO: 'Prato',
  PR: 'Parma',
  PT: 'Pistoia',
  PU: 'Pesaro e Urbino',
  PV: 'Pavia',
  PZ: 'Potenza',
  RA: 'Ravenna',
  RC: 'Reggio Calabria',
  RE: 'Reggio Emilia',
  RG: 'Ragusa',
  RI: 'Rieti',
  RM: 'Roma',
  RN: 'Rimini',
  RO: 'Rovigo',
  SA: 'Salerno',
  SI: 'Siena',
  SO: 'Sondrio',
  SP: 'La Spezia',
  SR: 'Siracusa',
  SS: 'Sassari',
  SU: 'Sud Sardegna',
  SV: 'Savona',
  TA: 'Taranto',
  TE: 'Teramo',
  TN: 'Trento',
  TO: 'Torino',
  TP: 'Trapani',
  TR: 'Terni',
  TS: 'Trieste',
  TV: 'Treviso',
  UD: 'Udine',
  VA: 'Varese',
  VB: 'Verbano-Cusio-Ossola',
  VC: 'Vercelli',
  VE: 'Venezia',
  VI: 'Vicenza',
  VR: 'Verona',
  VS: 'Sud Sardegna',
  VT: 'Viterbo',
  VV: 'Vibo Valentia',
};

export function provinciaFromSigla(sigla: string): string {
  const name = PROVINCIA_BY_SIGLA[sigla.toUpperCase()];
  if (!name) {
    throw new Error(`provinciaFromSigla: sigla sconosciuta "${sigla}". Aggiungerla alla tabella.`);
  }
  return name;
}
