/**
 * Schemi del dominio sessioni di tiro (Piano_Sviluppo_App.md §4.4, §6.1).
 */
import { z } from 'zod';
import { isoDateSchema, uuidSchema } from './common.js';

// ---------------------------------------------------------------------------
// Sessioni
// ---------------------------------------------------------------------------
export const sessionSchema = z.object({
  id: uuidSchema.optional(),
  rangeId: uuidSchema.nullable().optional(),
  bookingId: uuidSchema.nullable().optional(),
  /** Se il poligono non è censito, nome inserito manualmente. */
  rangeNameManual: z.string().max(200).nullable().optional(),
  startedAt: isoDateSchema,
  durationMinutes: z.number().int().positive(),
  distanceMeters: z.number().int().positive().optional(),
  autoGenerated: z.boolean().default(false),
  confirmedByUser: z.boolean().default(false),
  notes: z.string().max(5000).optional(),
});

export type Session = z.infer<typeof sessionSchema>;

export const createSessionSchema = sessionSchema.omit({ id: true, autoGenerated: true });

export type CreateSession = z.infer<typeof createSessionSchema>;

export const updateSessionSchema = createSessionSchema.partial();

export type UpdateSession = z.infer<typeof updateSessionSchema>;

export const sessionListResponseSchema = z.object({
  data: z.array(sessionSchema),
  nextCursor: z.string().nullable(),
  total: z.number().int().nonnegative().optional(),
});

export type SessionListResponse = z.infer<typeof sessionListResponseSchema>;

// ---------------------------------------------------------------------------
// Colpi sparati per sessione
// ---------------------------------------------------------------------------
export const sessionShotsSchema = z.object({
  sessionId: uuidSchema,
  firearmId: uuidSchema,
  caliber: z.string().min(1).max(50),
  roundsFired: z.number().int().positive(),
});

export type SessionShots = z.infer<typeof sessionShotsSchema>;

// ---------------------------------------------------------------------------
// Auto-generazione sessione da prenotazione
// ---------------------------------------------------------------------------
export const autoGenerateSessionSchema = z.object({
  bookingId: uuidSchema,
  /** Distanza effettiva di tiro (può differire da quella prenotata). */
  distanceMeters: z.number().int().positive().optional(),
  /** Calibro usato. */
  caliber: z.string().min(1).max(50).optional(),
  /** Colpi sparati. */
  roundsFired: z.number().int().positive().optional(),
});

export type AutoGenerateSession = z.infer<typeof autoGenerateSessionSchema>;

// ---------------------------------------------------------------------------
// Bersagli
// ---------------------------------------------------------------------------
export const targetSchema = z.object({
  id: uuidSchema.optional(),
  sessionId: uuidSchema,
  firearmId: uuidSchema,
  storageRef: z.string(),
  targetType: z.string().max(100).optional(),
  distanceMeters: z.number().int().positive().optional(),
  scoringMode: z.enum(['manuale', 'automatico']).default('manuale'),
});

export type Target = z.infer<typeof targetSchema>;

export const createTargetSchema = z.object({
  sessionId: uuidSchema,
  firearmId: uuidSchema,
  targetType: z.string().max(100).optional(),
  distanceMeters: z.number().int().positive().optional(),
});

export type CreateTarget = z.infer<typeof createTargetSchema>;

// ---------------------------------------------------------------------------
// Fori del bersaglio
// ---------------------------------------------------------------------------
export const targetHoleSchema = z.object({
  targetId: uuidSchema,
  xMm: z.number().finite(),
  yMm: z.number().finite(),
  score: z.number().nonnegative().optional(),
});

export type TargetHole = z.infer<typeof targetHoleSchema>;

export const markHolesSchema = z.object({
  holes: z.array(targetHoleSchema).min(1).max(200),
});

export type MarkHoles = z.infer<typeof markHolesSchema>;
